services:
  kproject.api:
    image: ghcr.io/wilasj/kproject:latest
    pull_policy: always
    environment:
      DOTNET_ENVIRONMENT: Production
      ConnectionStrings__Database: ${POSTGRES_URI}
    networks:
      - dokploy-network  
    expose:
      - 8080