services:
  kproject.api:
    image: kproject.api-local
    build:
      context: .
      dockerfile: KProject.Api/Dockerfile
      target: dev
      args:
        BUILD_CONFIGURATION: Debug
    environment:
      DOTNET_ENVIRONMENT: Development
    ports:
      - "8080:8080"

  kproject.database:
    ports:
      - "5432:5432"