<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
      <ProjectReference Include="..\KProject.Common\KProject.Common.csproj" />
      <ProjectReference Include="..\KProject.Infrastructure\KProject.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
      <PackageReference Include="Scrutor" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

</Project>
